# Why use Numpy

1) NumPy provides efficient storage


2) It also provides better ways if handling data for processing


3) It is fast


4) It is easy to learn


5) NumPy uses relatively less memory to store data

In [1]:
import numpy as np

In [12]:
 myarr = np.array([[3,6,32,7]], np.int64)

In [13]:
myarr

array([[ 3,  6, 32,  7]], dtype=int64)

In [14]:
myarr[0,0]

3

In [15]:
myarr[0,1]

6

In [17]:
myarr.shape

(1, 4)

In [18]:
myarr.dtype

dtype('int64')

In [19]:
myarr[0,1] = 45

In [20]:
myarr

array([[ 3, 45, 32,  7]], dtype=int64)

**Array Creation: Conversion from other python structures**

In [21]:
listarray = np.array([[1,2,3],[5,5,8],[0,3,1]])

In [22]:
listarray

array([[1, 2, 3],
       [5, 5, 8],
       [0, 3, 1]])

In [23]:
listarray.dtype

dtype('int32')

In [24]:
listarray.shape

(3, 3)

In [25]:
listarray.size

9

In [26]:
np.array({34,2,23})

array({34, 2, 23}, dtype=object)

**Array Creation : Intrinsic numpy array creation objects**

In [28]:
zeros = np.zeros((2, 5))

In [29]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
zeros.dtype

dtype('float64')

In [31]:
zeros.shape

(2, 5)

In [33]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
rng = np.arange(15)

In [35]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [42]:
lspace = np.linspace(1,5,4)

In [43]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [44]:
emp = np.empty((4,6))

In [45]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.33511290e-306, 6.23058368e-307, 8.45593934e-307],
       [7.56593017e-307, 1.11258854e-306, 1.11261502e-306,
        1.42410839e-306, 7.56597770e-307, 6.23059726e-307],
       [1.42419530e-306, 7.56602523e-307, 1.29061821e-306,
        1.37961234e-306, 9.34598926e-307, 1.33511562e-306],
       [9.34600963e-307, 8.45559303e-307, 8.06613040e-308,
        6.89810244e-307, 1.22387550e-307, 2.22522596e-306]])

In [46]:
emp_like = np.empty_like(lspace)

In [47]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [48]:
ide = np.identity(45)

In [49]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [51]:
ide.shape

(45, 45)

In [52]:
arr = np.arange(99)

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [55]:
arr = arr.reshape(3,33)

In [57]:
arr = arr.ravel()

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [60]:
arr.shape

(99,)